### ISSUE TITLE
timemachine 0.3.4 crashes on startup

### ISSUE THREAD

**Issue by fordfrog** [swh/timemachine#6]
i'm trying to package timemachine 0.3.4 on gentoo linux but cannot make the old 0.3.3 nor the 0.3.4 versions works. both crash on startup. here's the debug output:
```
$ gdb timemachine
GNU gdb (Gentoo 8.3.1 vanilla) 8.3.1
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from timemachine...
Reading symbols from /usr/lib/debug//usr/bin/timemachine.debug...
(gdb) run
Starting program: /usr/bin/timemachine 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7ffff624b700 (LWP 30757)]
[New Thread 0x7ffff60ce700 (LWP 30758)]
Jack: JackClient::SetupDriverSync driver sem in flush mode
Jack: JackLinuxFutex::Connect name = jack_sem.1000_default_TimeMachine
Jack: Clock source : system clock via clock_gettime
Jack: JackLibClient::Open name = TimeMachine refnum = 6
Jack: JackClient::Activate
Jack: JackPosixThread::StartImp : create non RT thread
[New Thread 0x7ffff5ba1700 (LWP 30759)]
Jack: JackPosixThread::ThreadHandler : start
Jack: JackClient::kBufferSizeCallback buffer_size = 64
Jack: JackClient::Init : period = 1333 computation = 500 constraint = 1333
Jack: JackPosixThread::AcquireRealTimeImp priority = 5
Jack: JackClient::ClientNotify ref = 6 name = TimeMachine notify = 2
Jack: JackClient::kActivateClient name = TimeMachine ref = 6 
Jack: JackClient::ClientNotify ref = 6 name = TimeMachine notify = 18
Jack: JackClient::ClientNotify ref = 6 name = TimeMachine notify = 18
Jack: JackClient::ClientNotify ref = 6 name = TimeMachine notify = 18
Jack: JackClient::ClientNotify ref = 6 name = TimeMachine notify = 18
Jack: JackClient::PortRegister ref = 6 name = TimeMachine:in_1 type = 32 bit float mono audio port_index = 87
Jack: JackClient::PortRegister ref = 6 name = TimeMachine:in_2 type = 32 bit float mono audio port_index = 88
[New Thread 0x7ffff5b20700 (LWP 30760)]
Jack: JackClient::ClientNotify ref = 6 name = TimeMachine notify = 18
Jack: JackClient::ClientNotify ref = 6 name = TimeMachine notify = 18
Jack: JackClient::ClientNotify ref = 6 name = TimeMachine notify = 18
Jack: JackClient::ClientNotify ref = 6 name = TimeMachine notify = 18

Thread 1 "timemachine" received signal SIGSEGV, Segmentation fault.
0x00007ffff7994c6b in type_node_check_conformities_UorL (have_lock=0, support_prerequisites=1, support_interfaces=1, iface_node=0x5555555ff170, node=0x55636660) at ../glib-2.60.7/gobject/gtype.c:3496
3496	  return type_node_check_conformities_UorL (node, iface_node, support_interfaces, support_prerequisites, FALSE);
(gdb) bt
#0  0x00007ffff7994c6b in type_node_check_conformities_UorL (have_lock=0, support_prerequisites=1, support_interfaces=1, iface_node=0x5555555ff170, node=0x55636660) at ../glib-2.60.7/gobject/gtype.c:3496
#1  0x00007ffff7994c6b in type_node_conforms_to_U (support_prerequisites=1, support_interfaces=1, iface_node=0x5555555ff170, node=0x55636660) at ../glib-2.60.7/gobject/gtype.c:3496
#2  0x00007ffff7994c6b in g_type_is_a (type=<optimized out>, iface_type=<optimized out>) at ../glib-2.60.7/gobject/gtype.c:3523
#3  0x00007ffff7d4c3d4 in gtk_type_new () at /usr/lib64/libgtk-x11-2.0.so.0
#4  0x000055555555af90 in gtk_meterscale_new (direction=direction@entry=8, min=min@entry=-60, max=max@entry=6) at gtkmeterscale.c:107
#5  0x0000555555558980 in create_window (title=<optimized out>) at interface.c:66
#6  0x000055555555804d in main (argc=<optimized out>, argv=<optimized out>) at main.c:323
(gdb)
``` 
i have no idea whether the problem is how timemachine calls glib or there is a bug in glib. i suppose you would know that :-)

**Comment by atsampson** [comment]
I fired up timemachine for the first time in 10-odd years and ran into this as well :-)

It's because gtkmeter/gtkmeterscale try to put a GtkType in a guint, and the latter isn't big enough on 64-bit platforms. I've just submitted a fix in #7.
